bind_addr = ":8088"
log_level = "debug"
mongo_uri = "mongodb://localhost:27018/?maxPoolSize=20&w=majority"
etherscan_api_key = "secret"
etherscan_api_url = "https://api.etherscan.io/api"
daemon_mode = true
load_transactions = 1000
session_key = ""